### PR TITLE
8040 Accomodate SSG during tests with longer step time allowance

### PR DESCRIPTION
**Pull request by godfreyyeung**
Fixes [AB#8040](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8040)

This fixes the tests by increasing the timeout for `start-server-and-test`, the utility used by Cypress to wait for a connection to localhost:3000.  Tests have been failing in Github Actions because SSG ran over the default timeout of start-server-and-test. 

See https://github.com/bahmutov/start-server-and-test

It also fixes some regressions in the geography spec due to copy and formatting changes.

### CODE REVIEW

**Review by horatiorosa — APPROVED** [review]
Seems like a decent amount time to wait to run the e2e

**Comment by godfreyyeung** [comment]
> Seems like a decent amount time to wait to run the e2e

Yeah maybe. Tyler said one category took 7 minutes in itself. If we have 5 categories, that's upwards of 35 minutes. We can definitely trim this down if it ends up being shorter than 30 minutes on average

**Comment by godfreyyeung** [comment]
> Seems like a decent amount time to wait to run the e2e

According to the tests, they ran in ~7 minutes. So I adjusted the timeout to be around double that for good measure: around 15 minutes.

**Comment by TylerMatteo** [comment]
>

**Comment by TylerMatteo** [comment]
> Seems like a decent amount time to wait to run the e2e

Yeah that definitely isn't normal but I'm fine with merging in this solution for now. I'm pretty sure the way you're supposed to handle this situation is to not do SSG for your e2e tests and have the pages built at run-time, like they are when you're doing local development. I'd like for us to get back to how the action workflows were originally implemented where they wouldn't continue to deployments for staging and prod if e2e tests failed but I don't think it's practical to do that until we figure out how to not need this timeout.

**Review by TylerMatteo — APPROVED** [review]
We should revisit how to run these tests without having to SSG the whole site but I think this is a great improvement over the current state of things.

**Comment by godfreyyeung** [comment]
> We should revisit how to run these tests without having to SSG the whole site but I think this is a great improvement over the current state of things.

Sounds great. Thanks!

**Pull request closed without merging**
